### ISSUE TITLE
no 'dist' or pre-bundled es2015 script is included 

### ISSUE THREAD

**Issue by iambumblehead** [facebook/react-vr#143]
### Description

No 'dist' or pre-bundled es2015 script is included. This makes react-vr difficult to "require" or "import" to another pre-existing application setup. Additionally, software such as 'detective' which follow the npm import/commonjs resolution rules are unable to follow the paths used in react-vr sources. 

For example, react-vr.js includes paths like this `return require('View');` which appear to reference files in paths like this 'Components/View/View.vr'

'node-detective', a common path resolution tool, fails to parse the react-vr script's newer ecmascript usage https://github.com/substack/node-detective/issues/70

Would you recommend a way to include react-vr "outside of" the deployment setup that comes with react-vr?

#### Expected behavior

an es2015 'dist' or 'build' file is included with react-vr that can be required/imported in another environment.

#### Actual behavior

no dist or build file is included

### Solution

add a dist or build file

### Additional Information

* React VR version: react-vr@1.0.0, react-vr-web@1.0.0
* Operating System: linux
* Graphics Card: intel
* Browser: chrome
* VR Device: out of vr

**Comment by andrewimm** [comment]
This is intentional behavior. Since React VR is based heavily off of React Native, and only capable of being built with the tooling there, it follows the same structure. We ship uncompiled ESNext + Flow + JSX because the tooling expects this. You should consider React VR to be the same as React Native for most purposes.

As a developer, I would also high recommend **against** trying to include React VR directly in another project. Instead, you should be embedding React VR experiences into larger applications as iframes, or similar. There is one exception: adding React VR as a UI layer to an existing Three.js project. We have some examples of that running internally to guarantee it works; the challenge is that your React VR application needs to be pre-built, or at least requested in the page before your script references the `ReactVR` global.

We're actively working with the React Native Packager team to continue supporting web-specific needs that go beyond the needs of React Native, but given the complexity of the application and the fact that we depend on a lot of RN internals, you shouldn't expect us to deliver precompiled packages anytime in the near future.

**Comment by iambumblehead** [comment]
Thanks for the explanation. I will close this issue.
