### ISSUE TITLE
Prevent click+drag from rotating camera on desktop?

### ISSUE THREAD

**Issue by nwoltman** [facebook/react-vr#166]
Is this possible?
For context, I'm trying to implement dragging around objects on desktop.

**Comment by andrewimm** [comment]
The click-drag is coming from the camera viewer, and not from the application.

You can think of React VR as two separate pieces: your application which describes how to build a 3d world, and a viewer that lets you see into the 3d world. The two operate completely separately, because the 3d scene shouldn't change based on your viewing device (within reason, there are things you might want to do differently in VR).

The piece of code that lets you maneuver this 3d world across desktop, mobile, and VR is known as the Player. You can specify the controls your app uses by tweaking the `controls` property of your application's Player. You can either attach a custom control scheme, or just turn off the mouse controls (recommended).

```
// client.js
const vr = new VRInstance(bundle, 'AppName', parent, {
  // Add custom options here
  ...options,
});
// Custom code here
// If you want to disable mouse controls AND mobile controls...
vr.player.controls.nonVRControls.disconnect();
// Alternatively, if you ONLY want to turn off the mouse controls...
const nonVRControls = vr.player.controls.nonVRControls;
if (nonVRControls instanceof require('ovrui').MousePanControls) {
  nonVRControls.disconnect();
}
```

Disconnecting the controls removes all event handlers, so your application will no longer respond to the click-drag input scheme.

**Comment by nwoltman** [comment]
That's exactly what I needed. Thanks @andrewimm!
