### ISSUE TITLE
Scenes on a mobile browser

### ISSUE THREAD

**Issue by OssamaZ** [facebook/react-vr#206]
### Description

On Desktop, you can click and drag around a scene. Aren't touch events supported on mobile browsers? 

Am i missing some configuration option?

**Comment by ichengde** [comment]
I think you are installing React VR through an existing document. Now the lastest react-vr code supports on mobile browsers for touch events. The reason that can not be supported for touch events is because GitHub code be updated but React VR code version of npm package is previous.
#### When the React VR team has not chosen to update React VR code version of npm package, you can through this way [#8681fc1](https://github.com/facebook/react-vr/commit/8681fc1b80999185fb0dafa43350006c0f417ac9) to test main build.

**Comment by andrewimm** [comment]
Fixed in 1.2.0 release.
