### ISSUE TITLE
[Feature Request] Swiping panorama on mobile phones

### ISSUE THREAD

**Issue by KhaledGabr** [facebook/react-vr#231]
By default, to rotate panoramas you have to rotate the device. But this is impractical if you are sitting on a chair. Rotating panoramas by swiping the touch screen is essential. It's allowed by default in a-frame along side with gyro sensor input.
Thanks for you consideration.

**Comment by andrewimm** [comment]
This has actually already been implemented in fc01746d9473e97f5daf5dbc9b18fb5a2a55f621

I'll try to release v1.2.0 of the packages within the next 24 hours, so we can get this and other key changes out.

**Comment by andelar** [comment]
Suggest re-open because it seems this only implements horizontal panning, unless I am missing something. Try laying down on the bed watching a scene on an iPhone... You end up staring up into the sky or down into the floor. For many scenes becomes an incomprehensible blue or white screen and most users abandon at that point. They try swiping but "nothing happens" (because you are just rotating around the Y axes while still staring up in the sky).
Compare how a pano is displayed and navigated on facebook.com or youtube.com which will be the experience expected by users (swipe in both X and Y directions).
Right now this is a show-stopper. Most viewers will be on their mobiles at first view, and they leave.

**Comment by andelar** [comment]
Confirm fixed in 1.4.0. Great!
