### ISSUE TITLE
Camera View zoomed-in on mobile Browsers

### ISSUE THREAD

**Issue by rawbknalb** [facebook/react-vr#233]
on iOS (Chrome and Safari) the Camera View is somehow zoomed in. Before the latest update of react vr I had a wider view on mobile. Did something change?

Tested on iPhone 7 Plus and iPad Pro (9.7)

**Comment by andrewimm** [comment]
Yes, zoom level is now kept constant when the device orientation changes. It used to be that changing your device's screen orientation forced a recalculation of the field of view, changing the zoom (because vertical FOV was kept at a constant 60 degrees). Now, when device orientation changes, we compute a new FOV angle that maintains the zoom level. This way, you know that your application will look the same, regardless of whether it's on its side or upright.

**Comment by andrewimm** [comment]
FYI, you can change the initial FOV and zoom by constructing a `THREE.PerspectiveCamera` at initialization time and passing it to your `new VrInstance()` call in `client.js`

**Comment by rawbknalb** [comment]
My problem was actually the initial FOV. Could somebody give me a code sample? I don‘t think that the initial FOV is correct... Again: Not the change of orientation is the problem. On Mobile I see a grainy pano image because of the initial zoom value. In my opinion it is a wrong value in the react vr library

**Comment by andrewimm** [comment]
The initial fov hasn't changed, it's always been fixed at 60 degrees, so unfortunately I'm not sure what caused the change you're seeing.

The easiest way to customize the camera's fov is to pass a value `calculateVerticalFOV: (width, height) => return some value` in the VrInstance initialization call in `client.js`. This is a function that takes the current window width and height, and determines the FOV. It does this at app initialization, and every time you resize the window or change the device orientation.
