### ISSUE TITLE
Support on React-VR

### ISSUE THREAD

**Issue by hjnieuwenhuizen** [facebook/react-vr#249]
hi guys, i know that this is only for submitting issues, but i am struggling to get any kind of support form the community. I have tried Stack Overflow and Discord with no luck. I know this is probably because React-VR is pretty new. The questions I have relate to an actual project we are trying to get off the ground. Can i submit my questions here regardless?

**Comment by jamonholmgren** [comment]
Hey @hjnieuwenhuizen! I normally wouldn't interject here with a shameless self-promotion, but since it's been 9 days of crickets, I'll make myself at home. 😄 

My company ([Infinite Red](https://infinite.red)) is currently in the process of adding React VR to our list of core services (joining React and React Native) and would like a few pilot projects. I can get you a discount off our normal hourly rate due to a lack of portfolio in this space. My team is very experienced with React and React Native, though, so we're not coming into it as rookies.

If you're interested in getting help from my awesome team, drop me a note at [jamon@infinite.red](mailto:jamon@infinite.red). If not, a friendly hi anyway from Portland. 😄

**Comment by amberroy** [comment]
If your questions are related to the React VR framework or gaps in our documentation feel free to submit them here. 

Thanks for your feedback @jamonholmgren please contact the developer directly for commercial services.
