### ISSUE TITLE
Image component uri Cross origin

### ISSUE THREAD

**Issue by Sepehr-Aliakbary70** [facebook/react-vr#315]
Hello I want to show a photo from external url. I wrote
```
<Image
  style={styles /* Some React Native styling */}
  source={{uri: 'http://facebook.github.io/react/img/logo_og.png'}}
 />
```
but I get the following error:
XMLHttpRequest cannot load ...

**Comment by andrewimm** [comment]
Here's the error message I get from chrome when running a similar fetch:

```
Fetch API cannot load http://facebook.github.io/react/img/logo_og.png. Redirect from 'http://facebook.github.io/react/img/logo_og.png' to 'https://facebook.github.io/react/img/logo_og.png' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8081' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

This is related to the configuration of Github's servers. The first request returns a 301 redirect to the https version of the image. Because there is no origin header on that first request, your browser (for safety reasons) assumes a different web domain should not be able to fetch it over an XMLHttpRequest, and cancels it. You can read more about this here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

The solution in this particular case would be to point to the https version. In general, you should have no trouble fetching images into React VR, particular your own images served from an endpoint you control.

**Comment by mattferrin** [comment]
I've found that many image URIs I grab off the internet do not work in the React 360 canvas, but do work in a normal img tag. None of the cloud storage providers seemed to work at first and there is something about the request response that is more picky for react-360 than for react-dom. Wish I understood better, as it doesn't seem to be CORS but something related or similar.

My original issue that I worked around:
https://stackoverflow.com/questions/51977137/react-360-image-uri-not-visible
