### ISSUE TITLE
ReactVR panoramic images vs Equirectangular images

### ISSUE THREAD

**Issue by TheMachineHere** [facebook/react-vr#326]
### Description
I am fairly new to ReactVR. I was trying out the pano component with normal panaromic images taken with my Android phone, and it seems to pixelated, while Equirectangular images seem to look great. 

I was wondering whether there is any way where we could use panaromic images to convert them into Equirectangular images, OR maybe there is a different component for panaromic images?

**Comment by amberroy** [comment]
You're correct that the pano component is for 360 images.  We don't have a component for 2D panoramic images, or a tools to convert them into Equirect.

**Comment by andrewimm** [comment]
One option for a traditional 2d panorama would be to use a <CylindricalLayer> (which wraps a 2d layout around the inside of a cylinder) and use a single <Image> there to show your panorama

**Comment by jgwinner** [comment]
You could also convert them through other means. My guess without knowing the particulars is that the pixelation can also be due to overall image size. Once you spread those pixels around a sphere, the resolution requirements explode.

I did some quick math - to make something look as detailed as on a 15 inch laptop at say a half a meter distance, it's roughly 17K pixels if my math is correct (and it could be wrong!)

== John ==

**Comment by TheMachineHere** [comment]
thank you.
