### ISSUE TITLE
[Feature Request] Guide or component to make 2D UI like Overlay class

### ISSUE THREAD

**Issue by darioodiaz** [facebook/react-vr#327]
### Description

Hi I was reading the source code and I find that Overlay class is used to make a 2D UI wtihin the camera that show the Vr Button and fullscreen button, there will be a guide to make this 2D UIs using Overlay class or will be a component released to archive this?

**Comment by darioodiaz** [comment]
any update or comment over this issue?

**Comment by jgwinner** [comment]
My guess is that it's not planned - although a response would be good, so PMFJI.

I have a question about the use case. From what I know - 2D UI's do not work well in 3D. It's *weird* to see things float in front of your eyes no matter where you turn your head. If you put the 2D UI in front of other screen space elements, it can make you sick, as your eyes say the item is behind, yet it's drawn in front, OR you get vergence-accommodation fatigue.

Or do you mean to display something in the web frame before the scene is shown in 3D? This might not show up depending on how the user is getting to the 3D scene.

How would this be used?

More explanation of how text is drawn though would always be good.

**Comment by darioodiaz** [comment]
I attach few examples cases that use 2D UI on a 3D/AR environment. I want to overlay text or images within the 3d world or environment, if you say that is better a 3D UI (like the button example in react-vr) I want to know how to fix it on the screen or move as the world camera does. I hope that explain better that I want to do, thanks.

[Black Mirror UI](https://daks2k3a4ib2z.cloudfront.net/58867455a932269c0f5a8c88/58e414da94f116a72a75544f_BlackMirror.jpg)

[Zelda UI](http://blog.ocad.ca/wordpress/vism2b15-fw2011-01/files/2011/09/targeting.jpg)

**Comment by andrewimm** [comment]
The Overlay class is used to create 2d UI for when you're on a standard web browser – it is not displayed in VR. You can find an example of how to use it here: https://github.com/facebook/react-vr/tree/master/Examples/DomOverlaySample

The idea is that some in-VR UIs don't display well on a small mobile screen, and it makes more sense to display them as a standard HTML layer above the canvas. Marcos covered this very well in our talk at Oculus Connect 4, though I unfortunately can't find a recording online. This effect can be seen in practice on http://vr.britishmuseum.org – loading it in 2d will use 2d overlays to inspect artifacts, while viewing in VR will show 3d panels.

If you want a UI that exists in VR, and is attached to the camera, I highly recommend attaching a secondary React root to the camera as demonstrated in this example: https://github.com/facebook/react-vr/tree/master/Examples/MultiRoot

**Comment by darioodiaz** [comment]
Thanks for your help @andrewimm I will look that examples and try it on my application. I close that issue because you reference an example for Overlay class

**Comment by neve32** [comment]
I new to know about 2d-UI  .it bit interesting to me .can u explain its boon and bane

**Comment by jgwinner** [comment]
The BlackMirror UI is actually a flat picture of what people think the UI would look like, but it's not actually IN VR/AR. The Zelda example isn't VR/AR, it's a regular 2D game.

They are 3D UI on a screen examples; there's quite a difference to viewing the world on a screen and being IN IT.

The problem with non-diegetic display (an  overlay) is that it breaks immersion. Once you see it, you KNOW you're not in a real environment, and this can destroy the R in VR.

The other problem is, where do you put the UI elements? If you put them 'over' everything in the world, you still have to display them in the left/right display. They WILL have a perceived depth. Where is this depth? If you put them in front of everything, but locate them at the neutral depth (say, 2-3 meters), then when you rotate your head and an object seems closer than the neutral position, it will still render 'behind' the display. This may make people puke, rip off the headset "something is wrong" or generally cause a ruckus. 

The British museum works really well because the displays are very carefully placed 'over' the background <pano> statement, so they look like floating signs in front of us. They even move a bit in relation to the background, making them seem real. They can never go into or behind an object because it's not 3D - it's just the background pano statement. If you mainly mark up Spherical 360, this kind of thing works well (and is pretty much built into React VR). The pano shots were made very carefully so that all objects are fairly distant from us - so the displays in front of the objects seem natural. It also works because the Pano backgrounds are NOT 3D (they are images mapped on a sphere), so everything looks really far away.

The British museum is not a 2D UI. They are flat objects positioned with 3D position. Think of them like billboards, all facing the point of view (which doesn't move).

If you make them actual 3D objects in the world, but rotate them with the camera, you'll need to very carefully control what objects are in front of your UI elements.

It is far, far better to make your UI actually part of the world. If you want to show health, show it on the hands of the avatar as blood. Allow a person to look 'down' and see themselves; as they get damaged, show them more beat up. 

This will make your app seem more real.

In real life, we don't walk around and see items floating in front of us.
