### ISSUE TITLE
Border of view is dentil, not line.

### ISSUE THREAD

**Issue by ngocnguyen09910060** [facebook/react-vr#336]
Hello everybody,
I has an issue. I create a popup using View, include some informations: image, title, description, price. 
`<View>
        <Pano source={asset('chess-world.jpg')}/>
        <View style={{
          width: 300,
          height: 500,
          backgroundColor: 'black'
        }}>
        ...
        </View>
      </View>`
When http://localhost:8081/vr/ is loaded, this popup is good. But when i rotate around panorama, border of view is dentil, not line. It isn't good. Please help me.
Thanks.

**Comment by andrewimm** [comment]
Sorry, can you provide a screenshot to demonstrate what you mean?

**Comment by ngocnguyen09910060** [comment]
Here is screenshot:
![untitled](https://user-images.githubusercontent.com/2366937/30520906-a9e527ca-9be0-11e7-88ce-14e6e2421e21.png)

**Comment by ngocnguyen09910060** [comment]
Hi @andrewimm , @amberroy,
Please help me.

**Comment by andrewimm** [comment]
@ngocnguyen09910060 React VR provides a flag to enable / disable Antialiasing. It is currently disabled by default, because ALL web applications using it (not just React VR) can cause rendering issues with Chrome on Samsung phones. Without antialiasing, you will see jagged lines like this.

To re-enable it, pass the flag `antialias: true` in your initialization call in client.js, but be aware that it may cause rendering issues with Samsung phones. Again, this is not specific to React VR in any way, but affects all WebGL apps.

**Comment by jgwinner** [comment]
Pardon me from Jumping in, but are you noticing that the edge isn't anti-aliased?

https://en.wikipedia.org/wiki/Spatial_anti-aliasing 

I've noticed this as well, but some of that is the way VR works to make the frame rates.  It's also browser dependent, and you didn't fill out the template asking for browser version, so it's hard for us to make recommendations. We really DO need that info to help you.

I would also be interested to know if ReactVR supports anti-aliasing. It looks like WebGL includes it, but whether it's implemented is up to the browsers.

I looked at the ReactVR code, and it looks like the default for antialiasing is true.

player.js:
   *   antialias: Enable antialiasing on the WebGLRenderer. Default is true.

If you are on FireFox, this answer about WebGL might help:

https://stackoverflow.com/questions/23501703/can-i-programmatically-enable-webgl-antialiasing-on-firefox#23510689 

So, my guess is that what you are looking for is not supported on your platform.

What browsers have you tried?
