### ISSUE TITLE
VideoPano cannot be viewed in headset using Carmel Developer Preview

### ISSUE THREAD

**Issue by tlakomy** [facebook/react-vr#356]
### Description

I'm using Carmel Developer Preview on Samsung S7 Edge and I'm not able to see a video when using a `VideoPano` component on a headset. I'm able to see the video just fine on both desktop and mobile.

#### Expected behavior
User should be able to see the video played by `VideoPano` component on headset.

#### Actual behavior
User is not able to see anything when using `VideoPano` component, apart from a white screen

### Reproduction

See here: https://github.com/facebook/react-vr/issues/310, I'm experiencing exactly the same issue.

### Additional Information

* 'react-vr' package version: 1.0.0
* 'react-vr-web' package version: 1.0.0
* Operating System: MacOS, I'm using a Macbook Air
* Graphics Card: Whatever Macbook Air uses
* Browser: Carmel Developer Preview
* VR Device: GearVR

**Comment by andrewimm** [comment]
Carmel Developer Preview is no longer maintained, and has not been updated for a while. You should be using Oculus Browser to test WebVR content on Samsung devices.

**Comment by tlakomy** [comment]
@andrewimm Is there any way for my app to redirect to Oculus Browser after clicking on "View in VR" button instead of Carmel Developer Preview?

**Comment by tlakomy** [comment]
I'd like to keep a flow of user going to a website on mobile, noticing the "View in VR" button, clicking it and after being prompted to insert the phone in VR headset going straight to VR mode.

**Comment by andrewimm** [comment]
The "View in VR" option is only available in VR browsers (Chrome for Android, Oculus Browser, Desktop Firefox), or in development builds on Samsung phones, since we still support developers who use it for debugging. However in this specific case, the bug is in the browser (which is no longer maintained), and will not be fixed.
Unless you explicitly allow it, when you build a production release of your app, you won't see the "View in VR" button on a non-VR-supported browser. This is because Carmel was a developer tool, and most Samsung users won't have it installed. It would be a poor experience to show a button that 90% of users can't use.

At the moment, Oculus Browser doesn't support deeplinking the way Carmel used to, because it has its own 2d browser view. Even so, that's unfortunately out of the scope of React VR, an unrelated JS library.

**Comment by tlakomy** [comment]
Thank you @andrewimm  for the detailed explanation, now it's much clearer to me :)

Have a good day!
