### ISSUE TITLE
Speech recognition for mobile.

### ISSUE THREAD

**Issue by venits** [facebook/react-vr#399]
Hi,
here is a thing.

#### Description (Feature Request)

I manage to add speech recognition to my app when It runs on PC with Chrome browser using [annyang](https://github.com/TalAter/annyang) as speech recognition library. It works pretty good :)

 Unfortunately on mobile I can't get positive result. I know, that It has to do with using microphone on mobile browser. I am wondering if there is any possibility for it to work? Can NativeModules help in this situation? 

I am really curious and I think if we manage to find solution, speech recognition could become a common part of this library ;)

**I just want to know if it's worth putting time to find solution or there is just no possible way for it to work.**

**Comment by andrewimm** [comment]
Are you saying that it works in a React VR desktop app, but not on mobile? Which browsers are you using on each platform?

This sounds like a browser issue, and unrelated to React VR, unless you can get it working in a standard web app in the same browser but not in React VR.

We're happy to help you create a good React VR integration for a speech recognition library, but I don't believe that speech should be a core part of the library at the moment. React VR is meant to be an easy way for developers to create complex user interfaces in 3d and VR, and it's designed to be as flexible as possible to allow add-ons (whether they're speech recognition or something else). This is similar to how React does not include a data management library directly, but instead allows developers to bring their own solutions in, thanks to the intentional flexibility of React.

**Comment by venits** [comment]
Yes, sorry it is no React VR problem for sure. Possibly there is something wrong with my microphone on mobile. I can get microphone on on mobile but it is not working right.

I used this site to test audio on desktop and mobile:
https://mdn.github.io/web-speech-api/speech-color-changer/

It only works on desktop. 
**I would be grateful if someone can test mobile microphone on this website and tell me if it works.**
