### ISSUE TITLE
OnRotationChange Callback

### ISSUE THREAD

**Issue by NishanthShankar** [facebook/react-vr#416]
Is it possible to get a callback when the camera is rotated. I would like move and reset elements based on the camera movement

**Comment by andrewimm** [comment]
Wouldn't that callback fire every frame? If you're on a mobile device or using a headset, the camera is constantly being updated, and your react code would be overloaded by trying to update itself every single frame.

It's much better to attach your head-locked objects directly to the camera, so that their position is automatically computed each frame. This multi-root example provides an exact demo of this behavior: https://github.com/facebook/react-vr/tree/master/Examples/MultiRoot
Alongside the main React scene, there's another set of React components that are mounted directly to the camera. Since they share the same JS context, you can easily share JS variables, or even a Redux store, between the two.
