### ISSUE TITLE
Detect if user is using mobile or not.

### ISSUE THREAD

**Issue by venits** [facebook/react-vr#419]
### Feature Request

I have noticed that using:
```javascript
import { Platform } from 'react-native';
```
Will always return **'vr'** and I believe that is how it supposed to be for WebVR no matter is you are using mobile or PC.

I found out that there is way to distinguish if user is on mobile or not.
In **client.js** you can check it like this:
```javascript
function init(bundle, parent, options) {
  vr = new VRInstance(bundle, 'SocialVrTest', parent, {
    ...options,
  });

  const isMobile = vr.player.isMobile;

  vr.start();
  return vr;
}
```

I didn't found this solution in docs so maybe it is good idea to put it somewhere.
I think that it may be useful for some developers :)

**Comment by andrewimm** [comment]
Correct, the platform is more the "parent system" than the actual device you're on. For instance, React Native uses the 'ios' platform for iPhone, iPad, and Apple TV, because they all use the same code for the most part. However, some features are implemented differently for the TV OS version, based on other flags like the mobile flag we expose.

As a web developer, I don't *love* the idea of using the `isMobile` flag in your application. We do it to change certain camera behaviors, but it's not a precise science, since we're using a user agent string that can be easily spoofed. That – along with the fact that you can easily run the check yourself – is why we don't mention it in any documentation.

Speaking generally about web development, it's better to toggle your application based on the supported behaviors of the platform than it is to assume a user agent string will guarantee behavior.
