### ISSUE TITLE
ASKING QUESTION ABOUT REACT VR

### ISSUE THREAD

**Issue by sanBastia** [facebook/react-vr#431]
### QUESTION 

on Google Chrome, after ENTER VR MODE, my VrButton doesnt work, but after EXIT VR MODE, i can use my VRButton via touching the screen device, but while ENTER VR MODE, it doesnt work with touching the device screen

* 'react-vr' package version: react-vr@1.2.0 
* 'react-vr-web' package version: react-vr-web@1.2.0
* Operating System: macOS and Linux Elementary distro
* Browser: Chrome
* VR Device: In VR device

**Comment by andrewimm** [comment]
Please read the documentation on input systems: https://facebook.github.io/react-vr/docs/input.html#cursor-systems

Out of the box, React VR does not ship with an in-VR cursor, because there are so many different scenarios that users may need to support. Given the current field of VR devices, we highly recommend you explore our 3dof/6dof system, available at https://github.com/facebook/react-vr/tree/master/packages/react-vr-controller-raycaster

It's also to possible to implement a gaze-based cursor for lesser systems that don't have physical remotes.  A number of community members have implemented these for users.

**Comment by jgwinner** [comment]
Just wanted to say, the raycaster is great! 

Raycasting works really well to do a gaze button too. I think there's an NPM for that. I covered it in my book but don't have the URL handy. @sanBastia let me know if you can't find it.

**Comment by sanBastia** [comment]
thank you @jgwinner ! well im using simple raycaster, it help me a lot to solve this problem, well thank you so much @andrewimm for the advice, without you, i will never know there is a "raycaster" in VR things !

**Comment by ajink024** [comment]
Do IHow do I clone the files to my computer? There is no link for this repo.

**Comment by tvalentius** [comment]
hi @ajink024 ,

You mean how to use this for project? you need to use NPM or Yarn to use it.

npm install -g react-vr-cli

or

yarn global add react-vr-cli

see the "getting started" part : https://github.com/facebook/react-vr

**Comment by ajink024** [comment]
No I only want to install the raycaster package into a project I have
created.
