### ISSUE TITLE
Live Streaming Video Pano

### ISSUE THREAD

**Issue by aziliak** [facebook/react-vr#446]
I haven't been able to find an answer on how to live-stream a video pano.  Is this option a possibility within ReactVR?

I tried using an Apple HLS but got the following error.

HTTP “Content-Type” of “application/vnd.apple.mpegurl” is not supported. Load of media resource 
Cannot play media. No decoders for requested formats: application/vnd.apple.mpegurl

**Comment by andrewimm** [comment]
Different video streams require custom players, since your browser may not support them. You can learn more here: https://facebook.github.io/react-vr/docs/video-player.html

We have included a demo of a DASH player, which is a common streaming format: https://github.com/facebook/react-vr/tree/master/Examples/DashSample

**Comment by aziliak** [comment]
Do you happen to have a good example using HLS?

**Comment by andrewimm** [comment]
Unfortunately, no, I'm not familiar with HLS. The error you report above is from your browser itself, which means the browser can't decode the HLS stream. You'll need to use a decoder that runs in JavaScript in order to get it to run, probably.

This isn't specific to React VR in any way, so I'll be closing this issue.
