### ISSUE TITLE
react-native-workers

### ISSUE THREAD

**Issue by FezVrasta** [facebook/react-vr#85]
How can I use react-native-workers in React VR?

Or use the native browser `Worker` API?

**Comment by andrewimm** [comment]
Can you provide more context on what you're trying to do?

If you're trying to spawn workers from within your react code, that should already be supported, as Web Workers are capable of spawning other Workers, assuming they have the same origin.

**Comment by FezVrasta** [comment]
I'm trying to run `new Worker` from within a module I import inside `index.vr.js`, but it throws an error complaining that `Worker` is not defined.

If I inspect the `window` object, it's actually **not** defined...

**Comment by andrewimm** [comment]
Sorry, I was quoting the spec, didn't realize that Blink-based browsers (chromium, etc) haven't yet implemented nested workers. This won't be possible until they're implemented, that's out of our control.

That said, what is the larger problem you're trying to solve? It should be completely feasible to implement a NativeModule that spins up new workers for computation, etc, and provides APIs to allow communication between your React context and the new workers.

**Comment by FezVrasta** [comment]
So, I have a module that uses a Worker to compute a bunch of stuff per second.

I have a:

```
new inst = new MyModule();
inst.on('tick', something);
```

I have tried to create a NativeModule like this:


```
import { Module } from 'react-vr-web';

export default class Worker extends Module {
  constructor() {
    super('MyModuleModule');
    this.callback = f => f;
    
    const engine = new MyModule();
    
    engine.on('tick', () => this.callback(this.serializeVertex(engine)));
  }
  
  onUpdate(callback) {
    this.callback = callback;
  }
  
  serializeVertex(engine) {
    const vertex = [];
    engine.eachVertex((ver) => {
      vertex.push(ver)
    });
    return vertex;
  }
}
```

But looks like I can't pass a callback between workers.... Any ideas?

**Comment by FezVrasta** [comment]
I think it would be enough to take advantage of the Worker messages, but I can't find a way to use them with NativeModules..

**Comment by andrewimm** [comment]
If you don't mind, I don't have the time right now, but I'd like to eventually try and put together a working sample of this in the next few days.

One thing to note, you can't re-use callbacks the way you have above. Rather than `onUpdate(callback)`, you need to emit events from the module to repeatedly trigger something in React.

In the meantime, this is approximately what I intend to implement (it may be enough).

```
// In React
const RCTDeviceEventEmitter = require('RCTDeviceEventEmitter');

RCTDeviceEventEmitter.addListener('myWorkerEvent', (e) => {
  // handle event
});
```

```
// In the runtime
export default class WorkerModule extends Module {
  constructor(rnctx) {
    super('WorkerModule');

    this._rnctx = rnctx;
    const engine = new MyModule();
    engine.on('tick', () => {
      const payload = serializeVertex(engine);
      this._rnctx.callFunction(
        'RCTDeviceEventEmitter',
        'emit',
        ['myWorkerEvent', payload]
      );
    });
  }

  // ...
}
```

React Native is in the process of implementing per-module event channels as well, but until that's finished their new API simply redirects to the main channel, so I'll avoid directing you to that API for now.

Following launch, I'll see if we can expose more of the worker setup to external configuration, so that Workers can be made to talk to each other directly. There's a bit of extra instrumentation that needs to happen to allow that, so we won't be able to get to that before React VR is released, but it's definitely something I'd want to support in the future.

**Comment by FezVrasta** [comment]
Thank you for your reply, looks exactly like what I need.

The only problem is that I get:

```
Uncaught ReferenceError: process is not defined
```

When I try your approach :(

**Comment by andrewimm** [comment]
I'd investigate whether this issue is coming from the code you're trying to import.

**Comment by FezVrasta** [comment]
It comes from `fbjs/lib/invariant`

**Comment by FezVrasta** [comment]
```
constructor(rnctx) {
```

Means I have to have:

```
import RCTDeviceEventEmitter from 'RCTDeviceEventEmitter'
import MyModule from './MyModule';

const myModule = new MyModule(RCTDeviceEventEmitter);

```
right?

**Comment by andrewimm** [comment]
Sorry, realized I left something out.

Since the VR Instance takes pre-initialized Modules, we need a reference to the ReactNativeContext that wraps the bridge. Here's a rewritten version of the above to account for this:

```
// WorkerModule.js
export default class WorkerModule extends Module {
  constructor() {
    super('WorkerModule');

    const engine = new MyModule();
    engine.on('tick', () => {
      // Make sure the RN context has been initialized
      if (this.rnctx) {
        const payload = serializeVertex(engine);
        this._rnctx.callFunction(
          'RCTDeviceEventEmitter',
          'emit',
          ['myWorkerEvent', payload]
        );
      });
    }
  }

  // ...
}
```

```
// client.js
import WorkerModule from './WorkerModule';

function init(bundle, parent, options) {
  const workerModule = new WorkerModule();
  const vr = new VRInstance(bundle, 'WorkerDemo', parent, {
    // Add custom options here
    nativeModules: [workerModule],
    ...options,
  });
  // Now that the rn context has been initialized, add it to the module
  workerModule.rnctx = vr.rootView.context;

  // ...
```

As for the `process is undefined` bit, can you a) tell me which version of react-vr, react-native, and fbjs are installed, b) give me the contents of your .babelrc file in the root of your project, and c) tell me if you've modified the build process in any way?

**Comment by FezVrasta** [comment]
Thank you so much for your help, I think I'm missing some piece of information here.

```
f (this.rnctx) {
        const payload = serializeVertex(engine);
        this._rnctx.callFunction(
```

You check `this.rnctx` but then you use `this._rnctx`, is that correct? On my app `_rnctx` is undefined, and `rnctx` is:


![image](https://cloud.githubusercontent.com/assets/5382443/24479347/b1907710-1493-11e7-93ba-c0c58279f506.png)


no `callFunction`

**Comment by andrewimm** [comment]
Sorry, yes, copypaste mistake. It should all be `this.rnctx`.

since callFunction is an instance method, you'll find it under the prototype definition in the chrome devtools

**Comment by FezVrasta** [comment]
Cool! It works, you saved my hackathon project 😄
