### ISSUE TITLE
Shininess, emissive and specular are not a property of this material in React VR

### ISSUE THREAD

**Issue by HeinPauwelyn** [facebook/react-vr#92]
## Description

I'm developing an application with React VR and I've created an 3D pokeball with blender. I've export this as Wavefront `.obj` file and use it in my React VR application.

In the console I see this warnings:

> **`THREE.MeshBasicMaterial`**: `shininess`, `emissive` and `specular` are not a property of this material.

Below you could find my code:

```jsx
import React from 'react';
import { AppRegistry, asset, StyleSheet, Pano, Text, View, Mesh } from 'react-vr';
    
class pokemongo extends React.Component {
  render() {
    return (
      <View>
        <Pano source={asset('sky.jpg')} />
        <Mesh source={{ mesh: asset('pokeball.obj'), mtl: asset('pokeball.mtl') }} 
              style={{ height: 1 }} 
              transform={{ rotate: '0 90 0' }}></Mesh>
      </View>
    );
  }
};
  
AppRegistry.registerComponent('pokemongo', () => pokemongo);
```

This is the rendered output

[![][1]][1]

And on [this GitHub Gist][2] you could find the `obj` and `mtl` file and could you download the `blend` file.

Here you could see my pokeball in Blender.

[![][3]][3]

I've searched on the internet but didn't found solutions or documentation about the problem related with React VR.

What I've done wrong?

  [1]: https://i.stack.imgur.com/7V0Os.jpg
  [2]: https://gist.github.com/HeinPauwelyn/32076ebfcd4dbd656b133d0cb87a782c
  [3]: https://i.stack.imgur.com/mLRFx.png

## Additional Information

* react-vr package version: ~0.1.0
* react-vr-web package version: ~0.1.0
* Operating System: Windows 10
* Graphics Card: NVIDA
* Browser: Chrome 56.0.2924.87, Edge 38.14393.0.0, Firefox 51.0.1
* VR Device: brouwser

## Personal notes

[See this question on Stack Overflow.][4]

[4]: http://stackoverflow.com/questions/42675253/shininess-emissive-and-specular-are-not-a-property-of-this-material-in-react-vr

**Comment by andrewimm** [comment]
Please update React VR to 0.2.1 or beyond. This has been resolved in recent versions.

**Comment by andrewimm** [comment]
Also, when you upgrade, be aware of these changes from 0.1 to 0.2:
https://facebook.github.io/react-vr/docs/release-change-log.html

The Mesh API has been significantly improved, so that at least will affect you.

There isn't a graceful way to upgrade from 0.1 to 0.2 (such is the risk with pre-1.0.0 APIs). The easiest way is to upgrade your cli (`npm install -g react-vr-cli`), then `react-vr init` a new project, and then copy your code to the new project directory. In the future there will not be such dramatic changes to project configuration.
